/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "dev_xesam_android_ndk_NdkTools.h"

jstring JNICALL Java_dev_xesam_android_ndk_NdkTools_getPackageName(JNIEnv* env, jclass clazz, jobject context){
    if(context == 0){
		return (*env)->NewStringUTF(env, "[+] Error: Context is 0");
	}

	jclass cls_context = (*env)->FindClass(env, "android/content/Context");
	if(cls_context == 0){
		return (*env)->NewStringUTF(env, "[+] Error: FindClass <android/content/Context> Error");
	}

	jmethodID getPackageName = (*env)->GetMethodID(env, cls_context, "getPackageName", "()Ljava/lang/String;");
	if(getPackageName == 0){
		return (*env)->NewStringUTF(env, "[+] Error: GetMethodID failed");
	}

	jstring packageName = (*env)->CallObjectMethod(env, context, getPackageName);
	if(packageName == 0){
		return (*env)->NewStringUTF(env, "[+] Error: CallObjectMethod failed");
	}else{
		return packageName;
	}
}
