/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_xesam_android_ndk_NdkTools */

#ifndef _Included_dev_xesam_android_ndk_NdkTools
#define _Included_dev_xesam_android_ndk_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_xesam_android_ndk_NdkTools
 * Method:    getPackageName
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_xesam_android_ndk_NdkTools_getPackageName
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_xesam_android_ndk_NdkTools
 * Method:    getDeviceId
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_xesam_android_ndk_NdkTools_getDeviceId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_xesam_android_ndk_NdkTools
 * Method:    getValue
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_dev_xesam_android_ndk_NdkTools_getValue
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
