/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "dev_xesam_android_ndk_NdkTools.h"
#include "ndk_tools.c"

jstring JNICALL Java_dev_xesam_android_ndk_NdkTools_getPackageName(JNIEnv* env, jclass clazz, jobject context){
    return Java_getPackageName(env, context);
}

jstring JNICALL Java_dev_xesam_android_ndk_NdkTools_getDeviceId(JNIEnv* env, jclass clazz, jobject context){
    return Java_getDeviceId(env, context);
}
